# Generated by Django 5.1.2 on 2024-11-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maintenancerequest_description_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='technician',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
