# Generated by Django 5.1.2 on 2024-11-01 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_technician_name_technician_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconditioner',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='airconditioner',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='airconditioner',
            name='installation_date',
            field=models.DateField(verbose_name='تاريخ التركيب'),
        ),
        migrations.AlterField(
            model_name='airconditioner',
            name='model',
            field=models.CharField(max_length=100, verbose_name='طراز الجهاز'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='air_conditioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airconditioner', verbose_name='جهاز التكييف'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technician', verbose_name='الفني المعين'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الطلب'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('In Progress', 'قيد التنفيذ'), ('Completed', 'مكتمل')], max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الفني'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='specialization',
            field=models.CharField(max_length=100, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
